name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: ls -la

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Укажите версию JDK, соответствующую вашему проекту
          distribution: 'adopt' # Это может быть 'adopt', 'zulu', 'temurin' и т.д.

      - name: Install Make
        run: sudo apt-get install make

      - name: Build project
        run: make build    # Используем Makefile для сборки проекта

      - name: Run tests
        run: make test     # Используем Makefile для запуска тестов

      - name: Generate report
        run: make report   # Генерация отчета (если необходимо)

      - name: Code Climate Test Reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          gem install codeclimate-test-reporter
          codeclimate-test-reporter before-build
          make test         # Запускаем тесты через Makefile
          codeclimate-test-reporter after-build
