name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Укажите версию JDK, соответствующую вашему проекту

      - name: Build with Gradle
        run: ./gradlew build # Если вы используете gradlew, иначе используйте gradle build

      - name: Run tests
        run: ./gradlew test # Запуск тестов

      - name: Code Climate Test Reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          gem install codeclimate-test-reporter
          codeclimate-test-reporter before-build
          ./gradlew test
          codeclimate-test-reporter after-build
