name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Make
        run: sudo apt-get install make

      - name: Build project
        run: make build

      - name: Run tests
        run: make -C app test         # Запускаем тесты через Makefile в директории app

      - name: Generate report
        run: make report              # Генерация отчета (если необходимо) из корневого Makefile

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make report  # Убедитесь, что ваша команда для генерации отчета верна
          coverageLocations: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
