name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la # Вывод содержимого каталога для отладки

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Makefile
        run: make setup # Настройка Gradle Wrapper

      - name: Build
        run: make build # Сборка проекта

      - name: Install
        run: make installDist

      - name: Run lint
        run: make lint # Запуск линтинга

      - name: Run tests
        run: make test # Запуск тестов

      - name: Generate coverage report
        run: make report # Генерация отчета Jacoco

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
           JACOCO_SOURCE_PATH: app/src/main/java
        with:
           coverageCommand: make report
           coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
           debug: true
