name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install Make
        run: sudo apt-get install -y make
        
      - name: Build project
        run: make build  # Запускаем сборку через Makefile в корневой директории

      - name: Run tests
        run: make -C app test  # Запускаем тесты из директории app

      - name: Run Checkstyle
        run: make -C app lint  # Запускаем линтинг через Checkstyle

      - name: Generate Jacoco report
        run: make -C app report --stacktrace --info
     
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make report  # Проверка на корректность команды
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          inputType: jacoco
