name: CI

name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain  # Запускаем Checkstyle

      - name: Run tests
        run: ./gradlew test  # Запускаем тесты

       # Uncomment this section if you need to publish code coverage
       - name: Publish code coverage
          uses: paambaati/codeclimate-action@v9.0.0
           env:
            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
            JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
         with:
            coverageCommand: make report
            coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
